spring:
  datasource:
    url: ENC(2Vo8lAdp3YQLip2+8mIytjPVParZ8cCFUSqOYfzPzvHjvqFiZOwGQCGyPM3vh1COhLUjxpk+uwcLe0r7yLAPfQiA4afuUcRfHijUeIiL37wICvaNrJy6K1WtKm2iyk8fshIhUNsItgE=)
    username: ENC(emSZzhxK7kiyy+DCvMw7ZMem8K+4Wflp)
    password: ENC(FghdAtCjugJtF4F3AzYk/GxbLH2W5WhP)

  jpa:
    hibernate:
      ddl-auto: validate

decorator:
  datasource:
    p6spy:
      enable-logging: false

