spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

decorator:
  datasource:
    p6spy:
      enable-logging: true
