spring:
  datasource:
    url: ENC(HpkvEA5gwl+GG6Ap/ZLmjR8cnjwuuE2GVxFiEDytCU6ydzVKruYECBbl+owHCZDqTE4DErMTPLsajl53MGlS6uOIZwn+KpKxlXEsC9nAh+uOezUWaFLJGg==)
    username: ENC(NSiBBX6KeUvNxHBnw9TD9jRZVfctkHYL)
    password: ENC(FghdAtCjugJtF4F3AzYk/GxbLH2W5WhP)

  jpa:
    hibernate:
      ddl-auto: validate

decorator:
  datasource:
    p6spy:
      enable-logging: false

